### ISSUE TITLE
Diğer Sunular

### ISSUE THREAD

**Issue by eersoy93** [emirozturk/Isletim-Sistemleri-2023-2024#1]
Merhaba Hocam,

Diğer sunuları da buraya atabilir misiniz? :)

Apple hesabım yok, diğer sunulara erişemedim.

Şimdiden teşekkür ederim.

**Comment by emirozturk** [comment]
Açmak için Apple hesabı istediğini bilmiyordum. En kısa zamanda animasyonları gösterebilecek bir format bulup tekrar yükleyeceğim. Pdf olanlar açıklamalı. Slaytlar birden fazla haftayı kapsadığı için tamamlandığında ek açıklamalarını ders notu olması adına ekleyip yükleyeceğim.
